// ============================================================
// GENERATED by hw/quartus/gen_addr_map.ps1 - DO NOT EDIT.
// Bridge-relative base offsets read from soc_system.sopcinfo.
// Regenerate after every qsys-generate.
// ============================================================
#ifndef SOC_ADDR_MAP_H
#define SOC_ADDR_MAP_H

#define BUTTON_PIO_BASE              0x0140
#define DIPSW_PIO_BASE               0x0130
#define FSM_STATUS_PIO_BASE          0x0110
#define ILC_BASE                     0x0000
#define JTAG_UART_BASE               0x20000
#define LED_PIO_BASE                 0x0120
#define MSG_TEXT_PIO_0_BASE          0x0400
#define MSG_TEXT_PIO_1_BASE          0x0410
#define MSG_TEXT_PIO_10_BASE         0x04A0
#define MSG_TEXT_PIO_11_BASE         0x04B0
#define MSG_TEXT_PIO_12_BASE         0x04C0
#define MSG_TEXT_PIO_13_BASE         0x04D0
#define MSG_TEXT_PIO_14_BASE         0x04E0
#define MSG_TEXT_PIO_15_BASE         0x04F0
#define MSG_TEXT_PIO_2_BASE          0x0420
#define MSG_TEXT_PIO_3_BASE          0x0430
#define MSG_TEXT_PIO_4_BASE          0x0440
#define MSG_TEXT_PIO_5_BASE          0x0450
#define MSG_TEXT_PIO_6_BASE          0x0460
#define MSG_TEXT_PIO_7_BASE          0x0470
#define MSG_TEXT_PIO_8_BASE          0x0480
#define MSG_TEXT_PIO_9_BASE          0x0490
#define MSG_TEXT_STATUS_PIO_BASE     0x0500
#define SYSID_QSYS_BASE              0x0150
#define TIMER_STATUS_PIO_BASE        0x0100

#endif // SOC_ADDR_MAP_H
