// ============================================================================
// GENERATED by hw/quartus/gen_addr_map.ps1 - DO NOT EDIT BY HAND.
// Bridge-relative base offsets read from soc_system.sopcinfo.
// Regenerate after every qsys-generate.
//
// PLACEHOLDER NOTICE: this copy was hand-derived from the pinned addresses
// requested in hw/quartus/add_pios.tcl (mm_bridge_0's address width is
// explicitly pinned to 12 bits with USE_AUTO_ADDRESS_WIDTH=0, and every PIO
// base below is set with an explicit set_connection_parameter_value call, not
// left to Qsys auto-assignment), so these values should already match what
// qsys-generate produces. Still: run gen_addr_map.ps1 after the first real
// qsys-generate on this machine and let it overwrite this file, so the
// address map is always sourced from the actual build, not a hand-copy.
// ============================================================================
#ifndef SOC_ADDR_MAP_H
#define SOC_ADDR_MAP_H

#define BUTTON_PIO_BASE               0x0140
#define DIPSW_PIO_BASE                0x0130
#define LED_PIO_BASE                  0x0120
#define FSM_STATUS_PIO_BASE           0x0110
#define TIMER_STATUS_PIO_BASE         0x0100

// Wide message-text bridge interface: 16 x 32-bit words (word w = text bytes
// 4w..4w+3, byte B=line*16+col) + status {seq[2:0], text_index[4:0]}.
#define MSG_TEXT_PIO_0_BASE           0x0400
#define MSG_TEXT_PIO_1_BASE           0x0410
#define MSG_TEXT_PIO_2_BASE           0x0420
#define MSG_TEXT_PIO_3_BASE           0x0430
#define MSG_TEXT_PIO_4_BASE           0x0440
#define MSG_TEXT_PIO_5_BASE           0x0450
#define MSG_TEXT_PIO_6_BASE           0x0460
#define MSG_TEXT_PIO_7_BASE           0x0470
#define MSG_TEXT_PIO_8_BASE           0x0480
#define MSG_TEXT_PIO_9_BASE           0x0490
#define MSG_TEXT_PIO_10_BASE          0x04A0
#define MSG_TEXT_PIO_11_BASE          0x04B0
#define MSG_TEXT_PIO_12_BASE          0x04C0
#define MSG_TEXT_PIO_13_BASE          0x04D0
#define MSG_TEXT_PIO_14_BASE          0x04E0
#define MSG_TEXT_PIO_15_BASE          0x04F0
#define MSG_TEXT_STATUS_PIO_BASE      0x0500

#endif // SOC_ADDR_MAP_H
