// ============================================================
// GENERATED by tools/gen_msg_tables.py - DO NOT EDIT BY HAND.
// Edit the message table / nav rules and regenerate.
// ============================================================

// action: 0=KEY1(next in cat) 1=KEY2(next cat) 2=KEY3(emergency) 3=TIMEOUT(script)
module msg_nav_rom (
    input  wire [4:0] cur_index,
    input  wire [1:0] action,
    output reg  [4:0] next_index
);
    always @(*) begin
        case ({cur_index, action})
            7'd0: next_index = 5'd1;
            7'd1: next_index = 5'd3;
            7'd2: next_index = 5'd16;
            7'd3: next_index = 5'd1;
            7'd4: next_index = 5'd2;
            7'd5: next_index = 5'd3;
            7'd6: next_index = 5'd16;
            7'd7: next_index = 5'd2;
            7'd8: next_index = 5'd0;
            7'd9: next_index = 5'd3;
            7'd10: next_index = 5'd16;
            7'd11: next_index = 5'd13;
            7'd12: next_index = 5'd4;
            7'd13: next_index = 5'd7;
            7'd14: next_index = 5'd16;
            7'd15: next_index = 5'd4;
            7'd16: next_index = 5'd5;
            7'd17: next_index = 5'd7;
            7'd18: next_index = 5'd16;
            7'd19: next_index = 5'd5;
            7'd20: next_index = 5'd6;
            7'd21: next_index = 5'd7;
            7'd22: next_index = 5'd16;
            7'd23: next_index = 5'd6;
            7'd24: next_index = 5'd3;
            7'd25: next_index = 5'd7;
            7'd26: next_index = 5'd16;
            7'd27: next_index = 5'd7;
            7'd28: next_index = 5'd7;
            7'd29: next_index = 5'd8;
            7'd30: next_index = 5'd16;
            7'd31: next_index = 5'd14;
            7'd32: next_index = 5'd9;
            7'd33: next_index = 5'd10;
            7'd34: next_index = 5'd16;
            7'd35: next_index = 5'd9;
            7'd36: next_index = 5'd8;
            7'd37: next_index = 5'd10;
            7'd38: next_index = 5'd16;
            7'd39: next_index = 5'd17;
            7'd40: next_index = 5'd11;
            7'd41: next_index = 5'd12;
            7'd42: next_index = 5'd16;
            7'd43: next_index = 5'd10;
            7'd44: next_index = 5'd10;
            7'd45: next_index = 5'd12;
            7'd46: next_index = 5'd16;
            7'd47: next_index = 5'd11;
            7'd48: next_index = 5'd13;
            7'd49: next_index = 5'd14;
            7'd50: next_index = 5'd16;
            7'd51: next_index = 5'd12;
            7'd52: next_index = 5'd12;
            7'd53: next_index = 5'd14;
            7'd54: next_index = 5'd16;
            7'd55: next_index = 5'd3;
            7'd56: next_index = 5'd15;
            7'd57: next_index = 5'd16;
            7'd58: next_index = 5'd16;
            7'd59: next_index = 5'd15;
            7'd60: next_index = 5'd14;
            7'd61: next_index = 5'd16;
            7'd62: next_index = 5'd16;
            7'd63: next_index = 5'd8;
            7'd64: next_index = 5'd16;
            7'd65: next_index = 5'd17;
            7'd66: next_index = 5'd16;
            7'd67: next_index = 5'd16;
            7'd68: next_index = 5'd17;
            7'd69: next_index = 5'd0;
            7'd70: next_index = 5'd16;
            7'd71: next_index = 5'd0;
            default: next_index = 5'd0;
        endcase
    end
endmodule
