# ============================================================================
# gen_addr_map.ps1 - generate sw/hps_app/soc_addr_map.h from the ACTUAL Qsys
# output, so the HPS never hand-types a bridge offset.
#
# Reads the generated soc_system.sopcinfo (produced by qsys-generate), extracts
# each Avalon slave's base address as seen from mm_bridge_0 (the LW H2F bridge
# master), and emits a header of #define <NAME>_BASE 0x.... offsets. Run this
# after every qsys-generate; if Qsys relocates a slave, the header follows
# automatically and main.c stays correct.
#
# Usage (from hw/quartus, after qsys-generate):
#   powershell -File gen_addr_map.ps1
# ============================================================================

$ErrorActionPreference = "Stop"

$here      = Split-Path -Parent $MyInvocation.MyCommand.Path
$sopcinfo  = Join-Path $here "soc_system.sopcinfo"
$outHeader = Join-Path $here "..\..\sw\hps_app\soc_addr_map.h"

if (-not (Test-Path $sopcinfo)) {
    Write-Error "soc_system.sopcinfo not found. Run qsys-generate first."
}

[xml]$doc = Get-Content $sopcinfo

# Find the memory connections mastered by mm_bridge_0 (the LW bridge). In a
# .sopcinfo, <connection> elements have kind='avalon', a <startModule> and
# <endModule>, and a <parameter name='baseAddress'>. We want connections whose
# start is the LW bridge master.
$map = @{}
foreach ($conn in $doc.EnsembleReport.connection) {
    if ($conn.kind -ne "avalon") { continue }
    if ($conn.startModule -notmatch "mm_bridge_0") { continue }
    $slave = $conn.endModule
    $base  = $null
    foreach ($p in $conn.parameter) {
        if ($p.name -eq "baseAddress") { $base = $p.value }
    }
    if ($null -ne $base) {
        # Normalize to an integer then to 0x hex.
        $val = [Convert]::ToInt64($base, ($(if ($base -match '^0x') {16} else {10})))
        $map[$slave] = $val
    }
}

if ($map.Count -eq 0) {
    Write-Error "No mm_bridge_0 slave connections found in the .sopcinfo. Check the master name."
}

$lines = @()
$lines += "// ============================================================"
$lines += "// GENERATED by hw/quartus/gen_addr_map.ps1 - DO NOT EDIT."
$lines += "// Bridge-relative base offsets read from soc_system.sopcinfo."
$lines += "// Regenerate after every qsys-generate."
$lines += "// ============================================================"
$lines += "#ifndef SOC_ADDR_MAP_H"
$lines += "#define SOC_ADDR_MAP_H"
$lines += ""
foreach ($name in ($map.Keys | Sort-Object)) {
    $macro = ($name.ToUpper() -replace '[^A-Z0-9]', '_') + "_BASE"
    $hex   = "0x{0:X4}" -f $map[$name]
    $lines += ("#define {0,-28} {1}" -f $macro, $hex)
}
$lines += ""
$lines += "#endif // SOC_ADDR_MAP_H"

Set-Content -Path $outHeader -Value $lines -Encoding ascii
Write-Host "Wrote $outHeader with $($map.Count) slave base addresses:"
foreach ($name in ($map.Keys | Sort-Object)) {
    Write-Host ("  {0,-24} 0x{1:X4}" -f $name, $map[$name])
}
